Added instructions for heroku
The existing .gitignore prevented all local settings from being pushed to Heroku, causing the following error when running syncdb:

File "/app/OpenDataCatalog/settings.py", line 236, in <module>
    LOCAL_STATICFILE_DIR,
NameError: name 'LOCAL_STATICFILE_DIR' is not defined